name: CI

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install .[dev]
      - name: Run pytest
        run: pytest -q
      - name: Upload replay excel
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: replay-excel
          path: outputs/
          if-no-files-found: warn
